trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    docker build -t basilvarghese/myapp-frontend:latest . -f Dockerfile
  displayName: 'build container image'

- script: |
    docker run basilvarghese/myapp-frontend:latest
  displayName: 'Run the application'
